fix(dependabot-recreate): verify input

diff --git a/.github/workflows/reusable-dependabot-recreate.yml b/.github/workflows/reusable-dependabot-recreate.yml
--- a/.github/workflows/reusable-dependabot-recreate.yml
+++ b/.github/workflows/reusable-dependabot-recreate.yml
@@ -31,6 +31,12 @@ jobs:
         uses: actions/checkout@v4
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
+      - name: Check if GITHUB_API_TOKEN is set
+        run: |
+          if [ -z "${{ secrets.GITHUB_API_TOKEN }}" ]; then
+            echo "::error::The GITHUB_API_TOKEN secret is not set. This is required for Dependabot PR recreation."
+            exit 1
+          fi
       - name: Comment on PRs
         run: |
           DEPENDABOT_PRS=$(
